### ISSUE TITLE
Deploy 

### ISSUE THREAD

**Issue by reddevil1310** [pedroprates/mobile-face-net#2]
Hi, i am beginner. I dont want to use google colab.
Can you deploy it with pycharm and local data?

**Comment by pedroprates** [comment]
Yes, it is possible to deploy it with PyCharm and local data. But it will take much longer if you do not have a GPU for training, which is my case, my GPU does not have CUDA support. May I ask why don't you want to use Google Colab? 

I'm currently working on updating the code to TensorFlow 2.0 and training on AWS SageMaker, which should speed things up (and also training with a larger dataset). Soon I will update the repository to the latest changes!

**Comment by reddevil1310** [comment]
I usually use Computer with GPU for training. I have never used google
colab, i don't know how to train and i am beginner in python. Can u help me
deploy with Pycharm and local data. Sorry i am not good at English?
Thank you ^^

Vào Th 5, 9 thg 7, 2020 vào lúc 20:26 Pedro Prates <
notifications@github.com> đã viết:
